/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

//import Control.EditUFPS;
import java.awt.Color;
//import util.ArchivoLeerURL;
//import com.itextpdf.text.DocumentException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import util.ArchivoLeerDocumento;

/**
 *
 * @author docenteauditorio
 */
public class Gui_Edit extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    int xMouse;
    int yMouse;

    /**
     * Creates new form Gui_Edit
     */
    private EditUFPS editufps;

    public Gui_Edit() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        initComponents();

        setIconImage(getIconImage());
        this.setLocationRelativeTo(this);
        Gui_Principal gp = new Gui_Principal();
        gp.pintarImagen(this.logo, "src/Vista/Images/ufps.PNG");
        gp.pintarImagen(this.logo2, "src/Vista/Images/logo_ingsistemas_vertical_invertido.png");
    }

    //Icono
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vista/Images/ufps_Icon.jpg"));
        return retValue;
    }

    public Gui_Edit(String url) {
        //https://gitlab.com/madarme/archivos-persistencia/-/raw/master/archivos%20texto%20plano/texto.txt

        initComponents();
        this.mostrarContenidoURL(url);
        setIconImage(getIconImage());
        this.setLocationRelativeTo(this);
        Gui_Principal gp = new Gui_Principal();
        gp.pintarImagen(this.logo, "src/Vista/Images/ufps.PNG");
        gp.pintarImagen(this.logo2, "src/Vista/Images/logo_ingsistemas_vertical_invertido.png");

    }

    public void Gui_Edit_Doc(String ruta) {
        initComponents();
        //this.mostrarContenidoDocumento(ruta);
    }

    private void mostrarContenidoURL(String url) {
        ArchivoLeerURL archivo = new ArchivoLeerURL(url);
        Object datos[] = archivo.leerArchivo();
        String texto = "";
        for (Object x : datos) {
            texto = x.toString() + "\n";
        }
        this.txtDocumento.setText(texto);
    }

    private void mostrarContenidoDocumento(String ruta) {

        ArchivoLeerDocumento archivo = new ArchivoLeerDocumento(ruta);

        Object datos[] = (Object[]) archivo.leer(ruta);
        String texto = "";
        for (Object x : datos) {
            texto = x.toString() + "\n";
        }
        this.txtDocumento.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        homeTxt = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        txt_logo = new javax.swing.JLabel();
        txt2_logo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDocumento = new javax.swing.JTextArea();
        btnGuardarListaCD = new javax.swing.JPanel();
        txtGuardarListaCD = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JLabel();
        btnReemplazar = new javax.swing.JPanel();
        txtReemplazar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        txtEliminar = new javax.swing.JLabel();
        btnGuardarPDF = new javax.swing.JPanel();
        txtPDF = new javax.swing.JLabel();
        btnGuardarPDFSubrayado = new javax.swing.JPanel();
        txtPDFSubrayado = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0, 0));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        exitTxt.setText(" X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        exitTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnHome.setBackground(new java.awt.Color(255, 255, 255));

        homeTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        homeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/home.png"))); // NOI18N
        homeTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homeTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        homeTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        homeTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        homeTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(homeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 1002, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        title.setFont(new java.awt.Font("Roboto Medium", 0, 62)); // NOI18N
        title.setText("EDIT UFPS");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        footer.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        footer.setText("Desarrolladores: José Gabriel Fuentes - 1152085 / Yeison Andrey Mantilla Sanabria - 1152088");
        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 652, 630, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/ads.png"))); // NOI18N
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 40));

        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 100));
        jPanel1.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 140, 160));

        txt_logo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txt_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt_logo.setText("Universidad Francisco");
        txt_logo.setToolTipText("");
        txt_logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txt2_logo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt2_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt2_logo.setText("de Paula Santander");
        jPanel1.add(txt2_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 30));

        jScrollPane1.setToolTipText("");
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDocumento.setEditable(false);
        txtDocumento.setColumns(20);
        txtDocumento.setFont(new java.awt.Font("Quicksand Medium", 0, 12)); // NOI18N
        txtDocumento.setRows(5);
        jScrollPane1.setViewportView(txtDocumento);
        txtDocumento.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 630, 390));

        btnGuardarListaCD.setBackground(new java.awt.Color(176, 21, 14));

        txtGuardarListaCD.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtGuardarListaCD.setForeground(new java.awt.Color(255, 255, 255));
        txtGuardarListaCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGuardarListaCD.setText("Guardar en ListaCD");
        txtGuardarListaCD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtGuardarListaCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGuardarListaCDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGuardarListaCDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtGuardarListaCDMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarListaCDLayout = new javax.swing.GroupLayout(btnGuardarListaCD);
        btnGuardarListaCD.setLayout(btnGuardarListaCDLayout);
        btnGuardarListaCDLayout.setHorizontalGroup(
            btnGuardarListaCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGuardarListaCD, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        btnGuardarListaCDLayout.setVerticalGroup(
            btnGuardarListaCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtGuardarListaCD, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardarListaCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 180, 50));

        btnBuscar.setBackground(new java.awt.Color(211, 89, 88));

        txtBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBuscar.setText("Buscar Palabra");
        txtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBuscar.setEnabled(false);
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 110, 50));

        btnReemplazar.setBackground(new java.awt.Color(211, 89, 88));

        txtReemplazar.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtReemplazar.setForeground(new java.awt.Color(255, 255, 255));
        txtReemplazar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReemplazar.setText("Reemplazar");
        txtReemplazar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtReemplazar.setEnabled(false);
        txtReemplazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReemplazarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtReemplazarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtReemplazarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnReemplazarLayout = new javax.swing.GroupLayout(btnReemplazar);
        btnReemplazar.setLayout(btnReemplazarLayout);
        btnReemplazarLayout.setHorizontalGroup(
            btnReemplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtReemplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnReemplazarLayout.setVerticalGroup(
            btnReemplazarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtReemplazar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnReemplazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, 50));

        btnEliminar.setBackground(new java.awt.Color(211, 89, 88));

        txtEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtEliminar.setForeground(new java.awt.Color(255, 255, 255));
        txtEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEliminar.setText("Eliminar");
        txtEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtEliminar.setEnabled(false);
        txtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 110, 50));

        btnGuardarPDF.setBackground(new java.awt.Color(211, 89, 88));

        txtPDF.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtPDF.setForeground(new java.awt.Color(255, 255, 255));
        txtPDF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPDF.setText("Guardar PDF");
        txtPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPDF.setEnabled(false);
        txtPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPDFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPDFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPDFMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarPDFLayout = new javax.swing.GroupLayout(btnGuardarPDF);
        btnGuardarPDF.setLayout(btnGuardarPDFLayout);
        btnGuardarPDFLayout.setHorizontalGroup(
            btnGuardarPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnGuardarPDFLayout.setVerticalGroup(
            btnGuardarPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 110, 50));

        btnGuardarPDFSubrayado.setBackground(new java.awt.Color(211, 89, 88));

        txtPDFSubrayado.setFont(new java.awt.Font("Roboto Medium", 0, 15)); // NOI18N
        txtPDFSubrayado.setForeground(new java.awt.Color(255, 255, 255));
        txtPDFSubrayado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPDFSubrayado.setText("PDF Subrayado");
        txtPDFSubrayado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPDFSubrayado.setEnabled(false);
        txtPDFSubrayado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPDFSubrayadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPDFSubrayadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPDFSubrayadoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarPDFSubrayadoLayout = new javax.swing.GroupLayout(btnGuardarPDFSubrayado);
        btnGuardarPDFSubrayado.setLayout(btnGuardarPDFSubrayadoLayout);
        btnGuardarPDFSubrayadoLayout.setHorizontalGroup(
            btnGuardarPDFSubrayadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPDFSubrayado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnGuardarPDFSubrayadoLayout.setVerticalGroup(
            btnGuardarPDFSubrayadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPDFSubrayado, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(btnGuardarPDFSubrayado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 110, 50));

        jLabelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/city2.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        btnExit.setBackground(new java.awt.Color(190, 0, 0));
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        btnExit.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void txtGuardarListaCDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGuardarListaCDMouseEntered
        this.btnGuardarListaCD.setBackground(new java.awt.Color(211, 89, 88));
        this.txtGuardarListaCD.setForeground(Color.white);
    }//GEN-LAST:event_txtGuardarListaCDMouseEntered

    private void txtGuardarListaCDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGuardarListaCDMouseExited
        this.btnGuardarListaCD.setBackground(new java.awt.Color(176, 21, 14));
        this.txtGuardarListaCD.setForeground(Color.white);
    }//GEN-LAST:event_txtGuardarListaCDMouseExited

    private void txtBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseEntered
        this.btnBuscar.setBackground(new java.awt.Color(176, 21, 14));
        this.txtBuscar.setForeground(Color.white);
    }//GEN-LAST:event_txtBuscarMouseEntered

    private void txtBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseExited
        this.btnBuscar.setBackground(new java.awt.Color(211, 89, 88));
        this.txtBuscar.setForeground(Color.white);
    }//GEN-LAST:event_txtBuscarMouseExited

    private void txtReemplazarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReemplazarMouseEntered
        this.btnReemplazar.setBackground(new java.awt.Color(176, 21, 14));
        this.txtReemplazar.setForeground(Color.white);
    }//GEN-LAST:event_txtReemplazarMouseEntered

    private void txtReemplazarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReemplazarMouseExited
        this.btnReemplazar.setBackground(new java.awt.Color(211, 89, 88));
        this.txtReemplazar.setForeground(Color.white);    }//GEN-LAST:event_txtReemplazarMouseExited

    private void txtEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseEntered
        this.btnEliminar.setBackground(new java.awt.Color(176, 21, 14));
        this.txtEliminar.setForeground(Color.white);
    }//GEN-LAST:event_txtEliminarMouseEntered

    private void txtEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseExited
        this.btnEliminar.setBackground(new java.awt.Color(211, 89, 88));
        this.txtEliminar.setForeground(Color.white);
    }//GEN-LAST:event_txtEliminarMouseExited

    private void txtPDFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPDFMouseEntered
        this.btnGuardarPDF.setBackground(new java.awt.Color(176, 21, 14));
        this.txtPDF.setForeground(Color.white);
    }//GEN-LAST:event_txtPDFMouseEntered

    private void txtPDFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPDFMouseExited
        this.btnGuardarPDF.setBackground(new java.awt.Color(211, 89, 88));
        this.txtPDF.setForeground(Color.white);
    }//GEN-LAST:event_txtPDFMouseExited

    private void txtPDFSubrayadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPDFSubrayadoMouseEntered
        this.btnGuardarPDFSubrayado.setBackground(new java.awt.Color(176, 21, 14));
        this.txtPDFSubrayado.setForeground(Color.white);
    }//GEN-LAST:event_txtPDFSubrayadoMouseEntered

    private void txtPDFSubrayadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPDFSubrayadoMouseExited
        this.btnGuardarPDFSubrayado.setBackground(new java.awt.Color(211, 89, 88));
        this.txtPDFSubrayado.setForeground(Color.white);
    }//GEN-LAST:event_txtPDFSubrayadoMouseExited

    private void txtGuardarListaCDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGuardarListaCDMouseClicked

        String texto = this.txtDocumento.getText();
        editufps = new EditUFPS(texto);
        JOptionPane.showMessageDialog(null, "Documento guardado en ListaCD", "EDIT UFPS", 3);

        /* char[] aCaracteres = texto.toCharArray();
        ListaCD<Character> l = new ListaCD();
        int i = 0;
        while (aCaracteres.length > i) {
            l.insertarFin(aCaracteres[i]);
            i++;
        }
        System.out.println(l.toString());*/
        this.txtBuscar.setEnabled(true);
        this.txtEliminar.setEnabled(true);
        this.txtReemplazar.setEnabled(true);
        this.txtPDF.setEnabled(true);
        this.txtPDFSubrayado.setEnabled(true);
    }//GEN-LAST:event_txtGuardarListaCDMouseClicked

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarMouseClicked
        //Panel_Buscar pB = new Panel_Buscar();
        //pB.setVisible(true);
        if (!editufps.documentEmpty()) {
            String palabra = JOptionPane.showInputDialog(null, "Palabra a buscar", "Edit_UFPS", JOptionPane.QUESTION_MESSAGE);
            if ((palabra != null) && (palabra.length() > 0)) {
                JOptionPane.showMessageDialog(null, "Hay " + editufps.buscar(palabra) + " palabra " + palabra, "Edit_UFPS", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            emptyDocumentError();
        }
    }//GEN-LAST:event_txtBuscarMouseClicked

    private void txtReemplazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReemplazarMouseClicked
        JTextField buscarField = new JTextField(10);
        JTextField reemplazarField = new JTextField(10);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Buscar:"));
        myPanel.add(buscarField);
        myPanel.add(Box.createHorizontalStrut(25)); // un espaciador
        myPanel.add(new JLabel("Reemplazar: "));
        myPanel.add(reemplazarField);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Ingrese los siguientes datos", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            String buscar = buscarField.getText();
            String reemplazar = reemplazarField.getText();

            //System.out.println("Buscar:" + buscar);
            //System.out.println("Reemplazar: " + reemplazar);
            EditUFPS texto = new EditUFPS(this.txtDocumento.getText());
            int totalReemplazos = texto.reemplazar(buscar, reemplazar);
            this.txtDocumento.setText(texto.listaToString());
            JOptionPane.showMessageDialog(null, "Se realizaron: " + totalReemplazos + " reemplazos", "Edit_UFPS",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            emptyDocumentError();
        }
    }//GEN-LAST:event_txtReemplazarMouseClicked

    private void txtEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseClicked
        if (!editufps.documentEmpty()) {
            String deleteText = JOptionPane.showInputDialog(null, "Palabra a eliminar", "Edit_UFPS", JOptionPane.QUESTION_MESSAGE);
            EditUFPS texto = new EditUFPS(this.txtDocumento.getText());
            int cantidadEliminada = texto.eliminar(deleteText);
            this.txtDocumento.setText(texto.listaToString());
            JOptionPane.showMessageDialog(null, "Se realizaron: " + cantidadEliminada + " eliminaciones", "Edit_UFPS",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            emptyDocumentError();
        }
    }//GEN-LAST:event_txtEliminarMouseClicked

    private void txtPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPDFMouseClicked
        if (!editufps.documentEmpty()) {
            String nombre = JOptionPane.showInputDialog(null, "Nombre del archivo pdf", "Edit_UFPS", JOptionPane.QUESTION_MESSAGE);
            if ((nombre != null) && (nombre.length() > 0)) {
                try {
                    editufps.crearPDF(nombre, txtDocumento.getText());
                } catch (DocumentException | FileNotFoundException ex) {
                    Logger.getLogger(Gui_Edit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else
            emptyDocumentError();
    }//GEN-LAST:event_txtPDFMouseClicked

    private void txtPDFSubrayadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPDFSubrayadoMouseClicked
        if (!editufps.documentEmpty()) {
            JTextField nombreArchivo = new JTextField(10);
            JTextField palabraSubrayar = new JTextField(10);

            JPanel myPanel = new JPanel();
            myPanel.add(new JLabel("Nombre del archivo:"));
            myPanel.add(nombreArchivo);
            myPanel.add(Box.createHorizontalStrut(35)); // un espaciador
            myPanel.add(new JLabel("Palabra a Subrayar: "));
            myPanel.add(palabraSubrayar);

            int result = JOptionPane.showConfirmDialog(null, myPanel,
                    "Ingrese los siguientes datos", JOptionPane.OK_CANCEL_OPTION);

            EditUFPS texto = new EditUFPS(this.txtDocumento.getText());

            texto.buscarYSubrayar(palabraSubrayar.getText());

            String name = nombreArchivo.getText();
            if ((name != null) && (name.length() > 0)) {
                try {
                    editufps.crearPDF(name, txtDocumento.getText());
                } catch (DocumentException | FileNotFoundException ex) {
                    Logger.getLogger(Gui_Edit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            emptyDocumentError();
        }


    }//GEN-LAST:event_txtPDFSubrayadoMouseClicked

    private void homeTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTxtMouseClicked
        Gui_Principal guiP = new Gui_Principal();
        guiP.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_homeTxtMouseClicked

    private void homeTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTxtMouseEntered
        btnHome.setBackground(new java.awt.Color(190, 0, 0));
        homeTxt.setForeground(Color.white);
    }//GEN-LAST:event_homeTxtMouseEntered

    private void homeTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTxtMouseExited
        btnHome.setBackground(Color.white);
        homeTxt.setForeground(Color.black);
    }//GEN-LAST:event_homeTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Edit().setVisible(true);
            }
        });
    }

    public void emptyDocumentError() {
        JOptionPane.showMessageDialog(null, "DOCUMENTO VACÍO", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public void setEditableGetTxtDocumento() {
        txtDocumento.setEditable(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnGuardarListaCD;
    private javax.swing.JPanel btnGuardarPDF;
    private javax.swing.JPanel btnGuardarPDFSubrayado;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnReemplazar;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel homeTxt;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel txt2_logo;
    private javax.swing.JLabel txtBuscar;
    private javax.swing.JTextArea txtDocumento;
    private javax.swing.JLabel txtEliminar;
    private javax.swing.JLabel txtGuardarListaCD;
    private javax.swing.JLabel txtPDF;
    private javax.swing.JLabel txtPDFSubrayado;
    private javax.swing.JLabel txtReemplazar;
    private javax.swing.JLabel txt_logo;
    // End of variables declaration//GEN-END:variables

}
