package Vista;

import gnu.io.*;
import static java.awt.image.ImageObserver.ERROR;
import java.awt.*;
import javax.swing.*;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jgfch
 */
public class JFrame_Sensor1 extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    int xMouse, yMouse;
    String text;
    //VARIABLES QUE PERMITEN ESTABLER LOS PARAMETROS DEL PUERTO 
    //Y CONEXION DEL MISMO
    SerialPort My_PuertoSerie;
    String PUERTO_IdName;
    private static final int TIMEOUT = 2000; //Milisegundos
    private static final int BAUD_RATE = 57600;
    //VARIABLES QUE CAPTURAN Y ENVIA LOS DATOS SERIALES
    private OutputStream output = null;
    private InputStream input_str = null;
    //PERMITE BUSCAR Y ENUMERAR TODOS LOS PUERTOS DISPONIBLES
    java.util.Enumeration<CommPortIdentifier> portEnum = CommPortIdentifier.getPortIdentifiers();

    /**
     * Creates new form JFrame_Sensor1
     */
    public JFrame_Sensor1() {
        initComponents();

        setIconImage(getIconImage());
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.logo, "src/Vista/Images/ufps.PNG");
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vista/Images/ufps_Icon.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        txt_logo = new javax.swing.JLabel();
        txt2_logo = new javax.swing.JLabel();
        txt_title = new javax.swing.JLabel();
        txt_title1 = new javax.swing.JLabel();
        jCbxPuertos = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JPanel();
        jBtnBuscar = new javax.swing.JLabel();
        btnConectar = new javax.swing.JPanel();
        jBtnConectar = new javax.swing.JLabel();
        btnDesconectar = new javax.swing.JPanel();
        jBtnDesconectar = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JPanel();
        jBtnEnrolar = new javax.swing.JLabel();
        btnAsistencia = new javax.swing.JPanel();
        jBtnDetectar = new javax.swing.JLabel();
        btnAsistencia1 = new javax.swing.JPanel();
        jBtnDetectar1 = new javax.swing.JLabel();
        btnAsistencia2 = new javax.swing.JPanel();
        jBtnDetectar2 = new javax.swing.JLabel();
        btnAsistencia3 = new javax.swing.JPanel();
        jBtnDetectar3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtArea = new javax.swing.JTextArea();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0, 0));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        exitTxt.setText(" X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        exitTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 1060, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 110));

        txt_logo.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txt_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt_logo.setText("Universidad Francisco");
        txt_logo.setToolTipText("");
        txt_logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txt2_logo.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txt2_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt2_logo.setText("de Paula Santander");
        jPanel1.add(txt2_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 30));

        txt_title.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txt_title.setForeground(new java.awt.Color(255, 255, 255));
        txt_title.setText("Toma de Asistencia ");
        txt_title.setToolTipText("");
        txt_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 290, -1));

        txt_title1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        txt_title1.setForeground(new java.awt.Color(255, 255, 255));
        txt_title1.setText("Dactilar");
        txt_title1.setToolTipText("");
        txt_title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jCbxPuertos.setEditable(true);
        jCbxPuertos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCbxPuertos.setEnabled(false);
        jPanel1.add(jCbxPuertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 210, 60));

        btnBuscar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnBuscar.setText("Buscar Puertos");
        jBtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 140, 60));

        btnConectar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnConectar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnConectar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnConectar.setText("Conectar");
        jBtnConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConectarLayout = new javax.swing.GroupLayout(btnConectar);
        btnConectar.setLayout(btnConectarLayout);
        btnConectarLayout.setHorizontalGroup(
            btnConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnConectarLayout.setVerticalGroup(
            btnConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 140, 60));

        btnDesconectar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnDesconectar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDesconectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnDesconectar.setText("Desconectar");
        jBtnDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDesconectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDesconectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDesconectarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDesconectarLayout = new javax.swing.GroupLayout(btnDesconectar);
        btnDesconectar.setLayout(btnDesconectarLayout);
        btnDesconectarLayout.setHorizontalGroup(
            btnDesconectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnDesconectarLayout.setVerticalGroup(
            btnDesconectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 140, 60));

        btnRegistrar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnEnrolar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnEnrolar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEnrolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnEnrolar.setText("Registrarse");
        jBtnEnrolar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnEnrolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEnrolarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnEnrolarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnEnrolarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnEnrolar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnEnrolar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 140, 60));

        btnAsistencia.setBackground(new java.awt.Color(211, 89, 88));

        jBtnDetectar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnDetectar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDetectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnDetectar.setText("Asistencia");
        jBtnDetectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnDetectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDetectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDetectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDetectarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAsistenciaLayout = new javax.swing.GroupLayout(btnAsistencia);
        btnAsistencia.setLayout(btnAsistenciaLayout);
        btnAsistenciaLayout.setHorizontalGroup(
            btnAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnAsistenciaLayout.setVerticalGroup(
            btnAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 140, 60));

        btnAsistencia1.setBackground(new java.awt.Color(211, 89, 88));

        jBtnDetectar1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnDetectar1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDetectar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnDetectar1.setText("Detener Asist");
        jBtnDetectar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnDetectar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDetectar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDetectar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDetectar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAsistencia1Layout = new javax.swing.GroupLayout(btnAsistencia1);
        btnAsistencia1.setLayout(btnAsistencia1Layout);
        btnAsistencia1Layout.setHorizontalGroup(
            btnAsistencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnAsistencia1Layout.setVerticalGroup(
            btnAsistencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnAsistencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 60));

        btnAsistencia2.setBackground(new java.awt.Color(211, 89, 88));

        jBtnDetectar2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnDetectar2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDetectar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnDetectar2.setText("Eliminar");
        jBtnDetectar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnDetectar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDetectar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDetectar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDetectar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAsistencia2Layout = new javax.swing.GroupLayout(btnAsistencia2);
        btnAsistencia2.setLayout(btnAsistencia2Layout);
        btnAsistencia2Layout.setHorizontalGroup(
            btnAsistencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnAsistencia2Layout.setVerticalGroup(
            btnAsistencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnAsistencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 140, 60));

        btnAsistencia3.setBackground(new java.awt.Color(211, 89, 88));

        jBtnDetectar3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnDetectar3.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDetectar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnDetectar3.setText("Borrar Todo");
        jBtnDetectar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnDetectar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDetectar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDetectar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDetectar3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAsistencia3Layout = new javax.swing.GroupLayout(btnAsistencia3);
        btnAsistencia3.setLayout(btnAsistencia3Layout);
        btnAsistencia3Layout.setHorizontalGroup(
            btnAsistencia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnAsistencia3Layout.setVerticalGroup(
            btnAsistencia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnAsistencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 140, 60));

        jTxtArea.setColumns(20);
        jTxtArea.setRows(5);
        jScrollPane1.setViewportView(jTxtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 570, 480));

        jLabelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/city2.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        btnExit.setBackground(new java.awt.Color(190, 0, 0));
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        btnExit.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void jBtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarMouseClicked
        while (portEnum.hasMoreElements()) {
            this.jBtnConectar.setEnabled(true);
            this.jCbxPuertos.setEnabled(true);
            CommPortIdentifier portIdentifier = portEnum.nextElement();
            String Mensajes = portIdentifier.getName() + " - " + getPortTypeName(portIdentifier.getPortType());
            String NombrePuertos = portIdentifier.getName();
            jTxtArea.append(Mensajes + "\n");
            jCbxPuertos.addItem(NombrePuertos);
        }
        
    }//GEN-LAST:event_jBtnBuscarMouseClicked

    private void jBtnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarMouseEntered
        this.btnBuscar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnBuscar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnBuscarMouseEntered

    private void jBtnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBuscarMouseExited
        this.btnBuscar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnBuscar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnBuscarMouseExited

    private void jBtnConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConectarMouseClicked
        CommPortIdentifier puertoID = null;
        java.util.Enumeration<CommPortIdentifier> listaPuertos = CommPortIdentifier.getPortIdentifiers();

        while (listaPuertos.hasMoreElements()) {
            CommPortIdentifier actualPuertoID = (CommPortIdentifier) listaPuertos.nextElement();
            PUERTO_IdName = jCbxPuertos.getSelectedItem().toString();
            if (PUERTO_IdName.equals(actualPuertoID.getName())) {
                puertoID = actualPuertoID;
                break;
            }
        }

        if (puertoID == null) {
            mostrarError("No se puede conectar al puerto");
            System.exit(ERROR);
        }

        try {
            My_PuertoSerie = (SerialPort) puertoID.open(this.getClass().getName(), TIMEOUT);
            My_PuertoSerie.setSerialPortParams(BAUD_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            input_str = My_PuertoSerie.getInputStream();
            output = My_PuertoSerie.getOutputStream();
            My_PuertoSerie.addEventListener(new SerialReader(input_str));
            My_PuertoSerie.notifyOnDataAvailable(true);

            jBtnConectar.setEnabled(false);
            jBtnDesconectar.setEnabled(true);
        } catch (Exception e) {
            mostrarError(e.getMessage());
            System.exit(ERROR);
        }
    }//GEN-LAST:event_jBtnConectarMouseClicked

    private void jBtnConectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConectarMouseEntered
        this.btnConectar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnConectar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnConectarMouseEntered

    private void jBtnConectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConectarMouseExited
        this.btnConectar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnConectar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnConectarMouseExited

    private void jBtnDesconectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDesconectarMouseClicked
        try{
            My_PuertoSerie.close();
            jBtnConectar.setEnabled(true);
            jBtnDesconectar.setEnabled(false);
           
        } catch(Exception e){
            mostrarError(e.getMessage());
            System.exit(ERROR);
        }
    }//GEN-LAST:event_jBtnDesconectarMouseClicked

    private void jBtnDesconectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDesconectarMouseEntered
        this.btnDesconectar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnDesconectar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnDesconectarMouseEntered

    private void jBtnDesconectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDesconectarMouseExited
        this.btnDesconectar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnDesconectar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnDesconectarMouseExited

    private void jBtnEnrolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEnrolarMouseClicked
        enviarDatos("E");
    }//GEN-LAST:event_jBtnEnrolarMouseClicked

    private void jBtnEnrolarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEnrolarMouseEntered
        this.btnRegistrar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnEnrolar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnEnrolarMouseEntered

    private void jBtnEnrolarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEnrolarMouseExited
        this.btnRegistrar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnEnrolar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnEnrolarMouseExited

    private void jBtnDetectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectarMouseClicked
        enviarDatos("H");
    }//GEN-LAST:event_jBtnDetectarMouseClicked

    private void jBtnDetectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectarMouseEntered
        this.btnAsistencia.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnDetectar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnDetectarMouseEntered

    private void jBtnDetectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectarMouseExited
        this.btnAsistencia.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnDetectar.setForeground(Color.white);
    }//GEN-LAST:event_jBtnDetectarMouseExited

    private void jBtnDetectar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar1MouseClicked

    private void jBtnDetectar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar1MouseEntered

    private void jBtnDetectar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar1MouseExited

    private void jBtnDetectar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar2MouseClicked

    private void jBtnDetectar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar2MouseEntered

    private void jBtnDetectar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar2MouseExited

    private void jBtnDetectar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar3MouseClicked

    private void jBtnDetectar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar3MouseEntered

    private void jBtnDetectar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnDetectar3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDetectar3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sensor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sensor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sensor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sensor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Sensor1().setVisible(true);
            }
        });
    }

    private void pintarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));

        lbl.setIcon(this.icono);
        this.repaint();
    }

//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
    private void enviarDatos(String datos) {
        try {
            output.write(datos.getBytes());
        } catch (Exception e) {
            mostrarError(e.getMessage());
            System.exit(ERROR);
        }
    }

    static String getPortTypeName(int portType) {
        switch (portType) {
            case CommPortIdentifier.PORT_SERIAL:
                return "Serial";
            default:
                return "unknown type";
        }
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    public class SerialReader implements SerialPortEventListener {

        private InputStream in;
        private byte[] buffer = new byte[1024];
        private StringBuffer cadena = new StringBuffer();
        private String cadena_aux;

        public SerialReader(InputStream in) {
            this.in = in;
        }

        public void serialEvent(SerialPortEvent arg0) {
            int data;

            try {
                cadena_aux = "";

                int len = 0;
                while ((data = in.read()) > -1) {
                    // El carácter de nueva línea (\n) es equivalente al 
                    // carácter de salto de línea ASCII (hex 0A)

                    if (data == '\n') {
                        //if ( data == '&' ) {//Determina que carater se considera como uno final del mensaje.
                        break;
                    }
                    buffer[len++] = (byte) data;
                    cadena = cadena.append((char) data);
                }

                cadena_aux = cadena.toString();

                //jTxtRecibir.setText("");
                //jTxtRecibir.setText(cadena.toString());

                jTxtArea.append(cadena_aux + "\n");
                cadena.delete(0, cadena.length());

                //A PARTIR DE AQUI ES NECESARIO UTILIZAR LAS VARIABLES
                //cadena_aux  => como string - pues es la unica variable que contiene los valores que ingresaron
                //buffer[x] = Contiene los datos en una matriz
                //int posicion = cadena_aux.indexOf("ID#1");
                //jTextField1.setText(Integer.toString(posicion));
                /*if (cadena_aux.indexOf("ID#1")==0) 
                {
                 jTxtRecibir.setText("");
                 jTxtRecibir.setText("INGRESO USUARIO 1");                
                }
                
                if (cadena_aux.indexOf("ID#2")==0) 
                {
                 jTxtRecibir.setText("");
                 jTxtRecibir.setText("INGRESO USUARIO 2");                
                }
                
                 if (cadena_aux.indexOf("ID#3")==0) 
                {
                 jTxtRecibir.setText("");
                 jTxtRecibir.setText("INGRESO USUARIO 3");                
                }*/
            } catch (Exception e) {
                mostrarError(e.getMessage());
            }
        }
    }

    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAsistencia;
    private javax.swing.JPanel btnAsistencia1;
    private javax.swing.JPanel btnAsistencia2;
    private javax.swing.JPanel btnAsistencia3;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnConectar;
    private javax.swing.JPanel btnDesconectar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jBtnBuscar;
    private javax.swing.JLabel jBtnConectar;
    private javax.swing.JLabel jBtnDesconectar;
    private javax.swing.JLabel jBtnDetectar;
    private javax.swing.JLabel jBtnDetectar1;
    private javax.swing.JLabel jBtnDetectar2;
    private javax.swing.JLabel jBtnDetectar3;
    private javax.swing.JLabel jBtnEnrolar;
    private javax.swing.JComboBox<String> jCbxPuertos;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtArea;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel txt2_logo;
    private javax.swing.JLabel txt_logo;
    private javax.swing.JLabel txt_title;
    private javax.swing.JLabel txt_title1;
    // End of variables declaration//GEN-END:variables
}
