package Vista;

import Modelo.Estudiante;
import gnu.io.*;
import static java.awt.image.ImageObserver.ERROR;
import java.awt.*;
import javax.swing.*;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jgfch
 */
public class SensorDactilar extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    int xMouse, yMouse;
    String text;
    //VARIABLES QUE PERMITEN ESTABLER LOS PARAMETROS DEL PUERTO 
    //Y CONEXION DEL MISMO
    SerialPort My_PuertoSerie;
    String PUERTO_IdName;
    private static final int TIMEOUT = 2000; //Milisegundos
    private static final int BAUD_RATE = 57600;
    //VARIABLES QUE CAPTURAN Y ENVIA LOS DATOS SERIALES
    private OutputStream output = null;
    private InputStream input_str = null;
    //PERMITE BUSCAR Y ENUMERAR TODOS LOS PUERTOS DISPONIBLES
    java.util.Enumeration<CommPortIdentifier> portEnum = CommPortIdentifier.getPortIdentifiers();

    /**
     * Creates new form JFrame_Sensor1
     */
    public SensorDactilar() {
        initComponents();

        setIconImage(getIconImage());
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.logo, "src/Vista/Images/ufps.PNG");
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vista/Images/ufps_Icon.jpg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        txt_logo = new javax.swing.JLabel();
        txt2_logo = new javax.swing.JLabel();
        txt_title = new javax.swing.JLabel();
        txt_title1 = new javax.swing.JLabel();
        jCbxPuertos = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JPanel();
        jBtnBuscar = new javax.swing.JLabel();
        btnConectar = new javax.swing.JPanel();
        jBtnConectar = new javax.swing.JLabel();
        btnDesconectar = new javax.swing.JPanel();
        jBtnDesconectar = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JPanel();
        jBtnEnrolar = new javax.swing.JLabel();
        btnAsistencia = new javax.swing.JPanel();
        jBtnDetectar = new javax.swing.JLabel();
        btnDetenerAsistencia = new javax.swing.JPanel();
        jBtnSalirDetec = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jBtnEliminar = new javax.swing.JLabel();
        btnBorrarTodo = new javax.swing.JPanel();
        jBtnBorrarTodo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtArea = new javax.swing.JTextArea();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 0, 0, 0));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        exitTxt.setText(" X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setMaximumSize(new java.awt.Dimension(40, 40));
        exitTxt.setMinimumSize(new java.awt.Dimension(40, 40));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 1060, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 110));

        txt_logo.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        txt_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt_logo.setText("Universidad Francisco");
        txt_logo.setToolTipText("");
        txt_logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txt2_logo.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        txt2_logo.setForeground(new java.awt.Color(255, 255, 255));
        txt2_logo.setText("de Paula Santander");
        jPanel1.add(txt2_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 30));

        txt_title.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        txt_title.setForeground(new java.awt.Color(255, 255, 255));
        txt_title.setText("Toma de Asistencia ");
        txt_title.setToolTipText("");
        txt_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 290, -1));

        txt_title1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        txt_title1.setForeground(new java.awt.Color(255, 255, 255));
        txt_title1.setText("Dactilar");
        txt_title1.setToolTipText("");
        txt_title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(txt_title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, -1));

        jCbxPuertos.setEditable(true);
        jCbxPuertos.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jCbxPuertos.setEnabled(false);
        jPanel1.add(jCbxPuertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 210, 60));

        btnBuscar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnBuscar.setText("Buscar Puertos");
        jBtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 140, 60));

        btnConectar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnConectar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnConectar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnConectar.setText("Conectar");
        jBtnConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnConectar.setEnabled(false);
        jBtnConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConectarLayout = new javax.swing.GroupLayout(btnConectar);
        btnConectar.setLayout(btnConectarLayout);
        btnConectarLayout.setHorizontalGroup(
            btnConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnConectarLayout.setVerticalGroup(
            btnConectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnConectar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 140, 60));

        btnDesconectar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnDesconectar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDesconectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnDesconectar.setText("Desconectar");
        jBtnDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnDesconectar.setEnabled(false);
        jBtnDesconectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDesconectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDesconectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDesconectarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDesconectarLayout = new javax.swing.GroupLayout(btnDesconectar);
        btnDesconectar.setLayout(btnDesconectarLayout);
        btnDesconectarLayout.setHorizontalGroup(
            btnDesconectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnDesconectarLayout.setVerticalGroup(
            btnDesconectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 140, 60));

        btnRegistrar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnEnrolar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnEnrolar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEnrolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnEnrolar.setText("Registrarse");
        jBtnEnrolar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnEnrolar.setEnabled(false);
        jBtnEnrolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEnrolarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnEnrolarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnEnrolarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnRegistrarLayout = new javax.swing.GroupLayout(btnRegistrar);
        btnRegistrar.setLayout(btnRegistrarLayout);
        btnRegistrarLayout.setHorizontalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnEnrolar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnRegistrarLayout.setVerticalGroup(
            btnRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnEnrolar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 140, 60));

        btnAsistencia.setBackground(new java.awt.Color(211, 89, 88));

        jBtnDetectar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnDetectar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDetectar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnDetectar.setText("Asistencia");
        jBtnDetectar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnDetectar.setEnabled(false);
        jBtnDetectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnDetectarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnDetectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnDetectarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAsistenciaLayout = new javax.swing.GroupLayout(btnAsistencia);
        btnAsistencia.setLayout(btnAsistenciaLayout);
        btnAsistenciaLayout.setHorizontalGroup(
            btnAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnAsistenciaLayout.setVerticalGroup(
            btnAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnDetectar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 140, 60));

        btnDetenerAsistencia.setBackground(new java.awt.Color(211, 89, 88));

        jBtnSalirDetec.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnSalirDetec.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSalirDetec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnSalirDetec.setText("Detener Asist");
        jBtnSalirDetec.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnSalirDetec.setEnabled(false);
        jBtnSalirDetec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSalirDetecMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnSalirDetecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnSalirDetecMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDetenerAsistenciaLayout = new javax.swing.GroupLayout(btnDetenerAsistencia);
        btnDetenerAsistencia.setLayout(btnDetenerAsistenciaLayout);
        btnDetenerAsistenciaLayout.setHorizontalGroup(
            btnDetenerAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnSalirDetec, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnDetenerAsistenciaLayout.setVerticalGroup(
            btnDetenerAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnSalirDetec, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnDetenerAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 60));

        btnEliminar.setBackground(new java.awt.Color(211, 89, 88));

        jBtnEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnEliminarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 140, 60));

        btnBorrarTodo.setBackground(new java.awt.Color(211, 89, 88));

        jBtnBorrarTodo.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jBtnBorrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBorrarTodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jBtnBorrarTodo.setText("Borrar Todo");
        jBtnBorrarTodo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnBorrarTodo.setEnabled(false);
        jBtnBorrarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnBorrarTodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnBorrarTodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnBorrarTodoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnBorrarTodoLayout = new javax.swing.GroupLayout(btnBorrarTodo);
        btnBorrarTodo.setLayout(btnBorrarTodoLayout);
        btnBorrarTodoLayout.setHorizontalGroup(
            btnBorrarTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnBorrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btnBorrarTodoLayout.setVerticalGroup(
            btnBorrarTodoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnBorrarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(btnBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 140, 60));

        jTxtArea.setColumns(20);
        jTxtArea.setRows(5);
        jScrollPane1.setViewportView(jTxtArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 570, 480));

        jLabelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Images/city2.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {                                     
        System.exit(0);
    }                                    

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {                                     
        btnExit.setBackground(new java.awt.Color(190, 0, 0));
        exitTxt.setForeground(Color.white);
    }                                    

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {                                    
        btnExit.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }                                   

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {                                    
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }                                   

    private void headerMousePressed(java.awt.event.MouseEvent evt) {                                    
        xMouse = evt.getX();
        yMouse = evt.getY();
    }                                   

    private void jBtnBuscarMouseClicked(java.awt.event.MouseEvent evt) {                                        
        while (portEnum.hasMoreElements()) {
            this.jBtnConectar.setEnabled(true);
            this.jCbxPuertos.setEnabled(true);
            CommPortIdentifier portIdentifier = portEnum.nextElement();
            String Mensajes = portIdentifier.getName() + " - " + getPortTypeName(portIdentifier.getPortType());
            String NombrePuertos = portIdentifier.getName();
            this.jTxtArea.append(Mensajes + "\n");
            this.jCbxPuertos.addItem(NombrePuertos);
        }

    }                                       

    private void jBtnBuscarMouseEntered(java.awt.event.MouseEvent evt) {                                        
        this.btnBuscar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnBuscar.setForeground(Color.white);
    }                                       

    private void jBtnBuscarMouseExited(java.awt.event.MouseEvent evt) {                                       
        this.btnBuscar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnBuscar.setForeground(Color.white);
    }                                      

    private void jBtnConectarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        if (!this.jBtnConectar.isEnabled()) {
            return;
        }
        CommPortIdentifier puertoID = null;
        java.util.Enumeration<CommPortIdentifier> listaPuertos = CommPortIdentifier.getPortIdentifiers();

        while (listaPuertos.hasMoreElements()) {
            CommPortIdentifier actualPuertoID = (CommPortIdentifier) listaPuertos.nextElement();
            PUERTO_IdName = jCbxPuertos.getSelectedItem().toString();
            if (PUERTO_IdName.equals(actualPuertoID.getName())) {
                puertoID = actualPuertoID;
                break;
            }
        }

        if (puertoID == null) {
            mostrarError("No se puede conectar al puerto");
            System.exit(ERROR);
        }

        try {
            My_PuertoSerie = (SerialPort) puertoID.open(this.getClass().getName(), TIMEOUT);
            My_PuertoSerie.setSerialPortParams(BAUD_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            input_str = My_PuertoSerie.getInputStream();
            output = My_PuertoSerie.getOutputStream();
            My_PuertoSerie.addEventListener(new SerialReader(input_str));
            My_PuertoSerie.notifyOnDataAvailable(true);

            this.jBtnConectar.setEnabled(false);
            this.jBtnDesconectar.setEnabled(true);
            this.jBtnBuscar.setEnabled(false);
            this.jBtnEnrolar.setEnabled(true);
            this.jBtnDetectar.setEnabled(true);
            this.jBtnEliminar.setEnabled(true);
            this.jBtnBorrarTodo.setEnabled(true);
        } catch (Exception e) {
            mostrarError(e.getMessage());
            System.exit(ERROR);
        }
    }                                         

    private void jBtnConectarMouseEntered(java.awt.event.MouseEvent evt) {                                          
        this.btnConectar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnConectar.setForeground(Color.white);
    }                                         

    private void jBtnConectarMouseExited(java.awt.event.MouseEvent evt) {                                         
        this.btnConectar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnConectar.setForeground(Color.white);
    }                                        

    private void jBtnDesconectarMouseClicked(java.awt.event.MouseEvent evt) {                                             
        if (!this.jBtnDesconectar.isEnabled()) {
            return;
        }
        try {
            My_PuertoSerie.close();
            this.jBtnBuscar.setEnabled(true);
            this.jBtnConectar.setEnabled(true);
            this.jBtnDesconectar.setEnabled(false);

        } catch (Exception e) {
            mostrarError(e.getMessage());
            System.exit(ERROR);
        }
    }                                            

    private void jBtnDesconectarMouseEntered(java.awt.event.MouseEvent evt) {                                             
        this.btnDesconectar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnDesconectar.setForeground(Color.white);
    }                                            

    private void jBtnDesconectarMouseExited(java.awt.event.MouseEvent evt) {                                            
        this.btnDesconectar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnDesconectar.setForeground(Color.white);
    }                                           

    private void jBtnEnrolarMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (!this.jBtnEnrolar.isEnabled()) {
            return;
        }
        enviarDatos("E");
        JTextField nameField = new JTextField(15);
        JTextField codeField = new JTextField(10);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Nombre:"));
        myPanel.add(nameField);
        myPanel.add(Box.createHorizontalStrut(25)); // un espaciador
        myPanel.add(new JLabel("Codigo: "));
        myPanel.add(codeField);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
                "Ingrese los siguientes datos", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            String nombre = nameField.getText();
            String code = codeField.getText();
            int codigo = Integer.valueOf(code);

            Estudiante estudiante = new Estudiante(nombre, codigo);
        } else {
            emptyDocumentError();
        }
    }                                        

    private void jBtnEnrolarMouseEntered(java.awt.event.MouseEvent evt) {                                         
        this.btnRegistrar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnEnrolar.setForeground(Color.white);
    }                                        

    private void jBtnEnrolarMouseExited(java.awt.event.MouseEvent evt) {                                        
        this.btnRegistrar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnEnrolar.setForeground(Color.white);
    }                                       

    private void jBtnDetectarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        if (!this.jBtnDetectar.isEnabled()) {
            return;
        }
        enviarDatos("H");
        this.jBtnSalirDetec.setEnabled(true);
        //this.jTxtArea.append("\nIngrese su Huella");
    }                                         

    private void jBtnDetectarMouseEntered(java.awt.event.MouseEvent evt) {                                          
        this.btnAsistencia.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnDetectar.setForeground(Color.white);
    }                                         

    private void jBtnDetectarMouseExited(java.awt.event.MouseEvent evt) {                                         
        this.btnAsistencia.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnDetectar.setForeground(Color.white);
    }                                        

    private void jBtnSalirDetecMouseClicked(java.awt.event.MouseEvent evt) {                                            
        if (!this.jBtnSalirDetec.isEnabled()) {
            return;
        }
        enviarDatos("X");
    }                                           

    private void jBtnSalirDetecMouseEntered(java.awt.event.MouseEvent evt) {                                            
        this.btnDetenerAsistencia.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnSalirDetec.setForeground(Color.white);
    }                                           

    private void jBtnSalirDetecMouseExited(java.awt.event.MouseEvent evt) {                                           
        this.btnDetenerAsistencia.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnSalirDetec.setForeground(Color.white);
    }                                          

    private void jBtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        if (!this.jBtnEliminar.isEnabled()) {
            return;
        }
        enviarDatos("D");//Delete
        String codigo = JOptionPane.showInputDialog(null, "Si desea eliminar una huella digite el codigo", "Sensor de Huella", JOptionPane.QUESTION_MESSAGE);

        if ((codigo != null) && (codigo.length() > 0)) {
            String IdEliminar = this.jTxtArea.getText();
            enviarDatos(IdEliminar);
            enviarDatos("\n");
            JOptionPane.showMessageDialog(null, "Se Borro la huella", "Sensor de Huella", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo borrar la huella", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }                                         

    private void jBtnEliminarMouseEntered(java.awt.event.MouseEvent evt) {                                          
        this.btnEliminar.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnEliminar.setForeground(Color.white);
    }                                         

    private void jBtnEliminarMouseExited(java.awt.event.MouseEvent evt) {                                         
        this.btnEliminar.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnEliminar.setForeground(Color.white);
    }                                        

    private void jBtnBorrarTodoMouseClicked(java.awt.event.MouseEvent evt) {                                            
        if (!this.jBtnBorrarTodo.isEnabled()) {
            return;
        }
        String password = JOptionPane.showInputDialog(null, "Si desea borrar todas las huellas digite la contraseña", "Sensor de Huella", JOptionPane.QUESTION_MESSAGE);
        String verify = "ingridlamejor";

        if (password.isEmpty()) {
            emptyDocumentError();
            return;
        }
        if ((password != null) && (password.length() > 0) && (password.equals(verify))) {
            enviarDatos("B");
            JOptionPane.showMessageDialog(null, "Se Borraron todas las huellas", "Sensor de Huella", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }                                           

    private void jBtnBorrarTodoMouseEntered(java.awt.event.MouseEvent evt) {                                            
        this.btnBorrarTodo.setBackground(new java.awt.Color(176, 21, 14));
        this.jBtnBorrarTodo.setForeground(Color.white);
    }                                           

    private void jBtnBorrarTodoMouseExited(java.awt.event.MouseEvent evt) {                                           
        this.btnBorrarTodo.setBackground(new java.awt.Color(211, 89, 88));
        this.jBtnBorrarTodo.setForeground(Color.white);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SensorDactilar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SensorDactilar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SensorDactilar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SensorDactilar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SensorDactilar().setVisible(true);
            }
        });
    }

    private void pintarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));

        lbl.setIcon(this.icono);
        this.repaint();
    }

    public void emptyDocumentError() {
        JOptionPane.showMessageDialog(null, "CASILLAS VACÍAS", "ERROR", JOptionPane.ERROR_MESSAGE);
    }

//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
    private void enviarDatos(String datos) {
        try {
            output.write(datos.getBytes());
        } catch (Exception e) {
            mostrarError(e.getMessage());
            System.exit(ERROR);
        }
    }

    static String getPortTypeName(int portType) {
        switch (portType) {
            case CommPortIdentifier.PORT_SERIAL:
                return "Serial";
            default:
                return "unknown type";
        }
    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);

    }

    public class SerialReader implements SerialPortEventListener {

        private InputStream in;
        private byte[] buffer = new byte[1024];
        private StringBuffer cadena = new StringBuffer();
        private String cadena_aux;

        public SerialReader(InputStream in) {
            this.in = in;
        }

        public void serialEvent(SerialPortEvent arg0) {
            int data;

            try {
                cadena_aux = "";

                int len = 0;
                while ((data = in.read()) > -1) {
                    // El carácter de nueva línea (\n) es equivalente al 
                    // carácter de salto de línea ASCII (hex 0A)

                    if (data == '\n') {
                        //if ( data == '&' ) {//Determina que carater se considera como uno final del mensaje.
                        break;
                    }
                    buffer[len++] = (byte) data;
                    cadena = cadena.append((char) data);
                }

                cadena_aux = cadena.toString();

                //jTxtRecibir.setText("");
                //jTxtRecibir.setText(cadena.toString());
                jTxtArea.append(cadena_aux + "\n");
                cadena.delete(0, cadena.length());

                //A PARTIR DE AQUI ES NECESARIO UTILIZAR LAS VARIABLES
                //cadena_aux  => como string - pues es la unica variable que contiene los valores que ingresaron
                //buffer[x] = Contiene los datos en una matriz
                //int posicion = cadena_aux.indexOf("ID#1");
                //jTextField1.setText(Integer.toString(posicion));
                /*if (cadena_aux.indexOf("ID#1")==0) 
                {
                 jTxtRecibir.setText("");
                 jTxtRecibir.setText("INGRESO USUARIO 1");                
                }
                
                if (cadena_aux.indexOf("ID#2")==0) 
                {
                 jTxtRecibir.setText("");
                 jTxtRecibir.setText("INGRESO USUARIO 2");                
                }
                
                 if (cadena_aux.indexOf("ID#3")==0) 
                {
                 jTxtRecibir.setText("");
                 jTxtRecibir.setText("INGRESO USUARIO 3");                
                }*/
            } catch (Exception e) {
                mostrarError(e.getMessage());
            }
        }
    }

//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
    // Variables declaration - do not modify                     
    private javax.swing.JPanel btnAsistencia;
    private javax.swing.JPanel btnBorrarTodo;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JPanel btnConectar;
    private javax.swing.JPanel btnDesconectar;
    private javax.swing.JPanel btnDetenerAsistencia;
    private javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnRegistrar;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jBtnBorrarTodo;
    private javax.swing.JLabel jBtnBuscar;
    private javax.swing.JLabel jBtnConectar;
    private javax.swing.JLabel jBtnDesconectar;
    private javax.swing.JLabel jBtnDetectar;
    private javax.swing.JLabel jBtnEliminar;
    private javax.swing.JLabel jBtnEnrolar;
    private javax.swing.JLabel jBtnSalirDetec;
    private javax.swing.JComboBox<String> jCbxPuertos;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtArea;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel txt2_logo;
    private javax.swing.JLabel txt_logo;
    private javax.swing.JLabel txt_title;
    private javax.swing.JLabel txt_title1;
    // End of variables declaration                   
}
